INSERT INTO clientes (nombre, apellido, email, create_at foto) VALUES ('Fabian', 'Veschi', 'fveschi@gmail.com', '2023-07-27', '')
    INSERT INTO clientes (nombre, apellido, email, create_at foto) VALUES ('Fede', 'Vera', 'fedevera@gmail.com', '2023-07-27', '')
    INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Agus', 'Lupa', 'agus@gmail.com', '2023-07-27', '')
    INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Mat', 'Lup', 'matlup@gmail.com', '2023-07-27', '')
    INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Ivan', 'Valeff', 'ivan@gmail.com', '2023-07-27', '')
    INSERT INTO clientes (nombre, apellido, email, create_at, foto) VALUES ('Fabian','Veschi', 'asdsa@gmail.com', 2023-09-10', '')